name: reusable-linter
run-name: "reusable linter: ${{ github.event_name == 'pull_request' && github.event.pull_request.title || github.ref_name }}"

on:
  workflow_call:
    inputs:
      actionlint:
        default: true
        required: false
        type: boolean
      shellcheck:
        default: true
        required: false
        type: boolean
      terraform-fmt:
        default: true
        required: false
        type: boolean
      terragrunt-hcl-fmt:
        default: true
        required: false
        type: boolean
      tflint:
        default: true
        required: false
        type: boolean
      trivy-config:
        default: true
        required: false
        type: boolean

  workflow_dispatch:
    inputs:
      actionlint:
        default: true
        required: false
        type: boolean
      shellcheck:
        default: true
        required: false
        type: boolean
      terraform-fmt:
        default: true
        required: false
        type: boolean
      terragrunt-hcl-fmt:
        default: true
        required: false
        type: boolean
      tflint:
        default: true
        required: false
        type: boolean
      trivy-config:
        default: true
        required: false
        type: boolean

permissions:
  contents: read

jobs:
  # github action workflow linter
  actionlint:
    if: ${{ inputs.actionlint }}
    runs-on: ubuntu-24.04
    steps:
      - &checkout_action
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
      - uses: docker://rhysd/actionlint:1.7.12@sha256:b1934ee5f1c509618f2508e6eb47ee0d3520686341fec936f3b79331f9315667
        with:
          args: -color

  # shell script linter
  shellcheck:
    if: ${{ inputs.shellcheck }}
    runs-on: ubuntu-24.04
    steps:
      - *checkout_action
      - uses: ludeeus/action-shellcheck@00cae500b08a931fb5698e11e79bfbd38e612a38 # 2.0.0
        with:
          scandir: .

  # terraform syntax linter
  terraform-fmt:
    if: ${{ inputs.terraform-fmt }}
    runs-on: ubuntu-24.04
    steps:
      - *checkout_action
      - uses: docker://ghcr.io/ulfiac/terraform-fmt:1.15.9@sha256:867d9b62038aaefaba0658d169bbdbb10758f2829bac5f47d698c02fd400304e
        with:
          args: -check -diff -recursive .

  # hcl syntax linter
  terragrunt-hcl-fmt:
    if: ${{ inputs.terragrunt-hcl-fmt }}
    runs-on: ubuntu-24.04
    steps:
      - *checkout_action
      - uses: docker://ghcr.io/ulfiac/terragrunt-hcl-fmt:1.1.3@sha256:5bfd7802bba9d2d703582396888968e19b83830c97d07edc5ac17628db7d5180
        with:
          args: --check --diff .

  # terraform linter
  tflint:
    if: ${{ inputs.tflint }}
    runs-on: ubuntu-24.04
    steps:
      - *checkout_action
      - uses: docker://ghcr.io/ulfiac/tflint:0.64.0@sha256:40badbe484b5f85a498066a14b3895594d46f319df83459d5d434b7ce5322684
        with:
          args: --recursive --color

  # security scanner
  trivy-config:
    if: ${{ inputs.trivy-config }}
    runs-on: ubuntu-24.04
    steps:
      - *checkout_action
      - uses: aquasecurity/trivy-action@ed142fd0673e97e23eac54620cfb913e5ce36c25 # v0.36.0
        with:
          scan-type: config
          scan-ref: .
          exit-code: '1'
          trivyignores: .trivyignore.yaml
